language: node_js

services:
  - docker

install: skip

script:
- docker build -f Dockerfile.dev -t temp_travis_image .
- docker run -e "CI=true" temp_travis_image npm test


# build the prod image, which actually just runs nginx
# before_deploy:
  # - docker build -t temp_travis_image .

# note: this is skipped on pull request builds. then when does it run?
# want to deploy that nginx + node image to elastic beanstalk
# deploy:
  # provider: elasticbeanstalk
