language: node_js

branches:
  only:
  - master

services:
  - docker

install: skip

script:
- docker build -f Dockerfile.dev -t temp_travis_image .
- docker run -e "CI=true" temp_travis_image npm test


# note: this is skipped on pull request builds. then when does it run?
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-course-frontend"
  env: "docker-course-frontend-env"
  bucket: "elasticbeanstalk-us-east-2-739614015117"
  bucket_path: "docker-course-frontend"
  on:
    branch: master